title: 程序设计语言 II
description: UNDER CONSTRUCTION
theme: just-the-docs

url: https://abotw.github.io/cpp

aux_links:
  Repo: https://github.com/abotw/cpp
  人大学院: https://www.hfuu.edu.cn/aibd/
  C++ compiler: https://pythontutor.com/cpp.html#mode=edit

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/favicon.ico"

math: katex

back_to_top: true
back_to_top_text: "回到顶部"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
